#Database configuration for MySql Dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beer_invenroty_dev
    username: beer_inventory_user
    password: password
    platform: mysql
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: false